### ISSUE TITLE
Use an open source website!

### ISSUE THREAD

**Issue by vmesel** [Lacsap-/pokemon-go-status#1]
There is a repo in my GitHub of a website that is already up and running called https://ispgo.net ! It could help the project keep it's open source quality!

**Comment by pboardman** [comment]
Hello!

I think the website I use works well for now.

Also I just checked and both website don't show the same status.

`http://cmmcd.com/PokemonGo/`: Unstable!

`https://ispgo.net`: Good ping 1

The server were clearly having problems when I checked so I'll keep the other website for now. But thanks for your suggestion!

**Comment by vmesel** [comment]
@Lacsap- do you know the URL this guys are pinging? I need to know it so I can create an API!

**Comment by pboardman** [comment]
No idea, send an email to contact@cmmcd.com he might tell you :)

**Comment by vmesel** [comment]
Tried to contact cmmcd and had no response, but, I could improve my system and now I can get a better system view: https://ispgo.net/api/
It is not a fully functional API, but it returns the JSON used by our system to get the system status!
