### ISSUE TITLE
Add pyobjc to dependencies.

### ISSUE THREAD

**Issue by huseyinyilmaz** [Lacsap-/pokemon-go-status#3]
Hello,
First of all thank you for the project. This is exactly what I was looking for :).

First time I used it I used it from the release. Than I realized that release was version 0.1 and there were already a 0.2 version. So I got the master and build from there. I was able to build it by fixing some py2app bug manually as explained here:

http://stackoverflow.com/a/29449144/350127

After that I was able to build the package but when I ran the package it did not work and got some error. I fixed it by adding pyobjc package to virtualenv I used to build the app as explained here:

http://stackoverflow.com/a/18043508/350127

For the people who use this. pyobjc is a build time dependency. It seems like if it is being added to app package. So you do not need to add it to global python path. It just needs to be on the path when you build the app.

It would be nice to have those tricks on README of this repo and pyobjc on requirements.txt

**Comment by pboardman** [comment]
Hi!

I'm happy you like the project! :)

What version of py2app did you use? I had no problem using py2app 0.7.2. I'll still add the stackoverflow link to the README.md so people who get your problem can build the app.

for your other point, I didn't realize pyobjc was required since I already had it installed, I'll add it to the requirements.txt !

Thank you for your input!

**Comment by huseyinyilmaz** [comment]
From pip-freeze I am getting following version. Actually I just created a new virtualenv and installed requirements file there. Here is the version that was installed:
py2app==0.10

**Comment by pboardman** [comment]
That's weird that I didn't have your problem with the same version, probably something configured diferently on my machine. Anyway, I'll keep the py2app fix in the README in case someone run into the problem!

I'll close the issue now, if you have something to add don't hesitate to reopen it or create a new one :)
